services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-barberbook}
      POSTGRES_USER: ${POSTGRES_USER:-barber}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-barberpass}
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  barberbook-api:
    build:
      context: .
      dockerfile: BarberBook.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080

      # (1) ConnectionStrings padrão
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=${POSTGRES_DB:-barberbook};Username=${POSTGRES_USER:-barber};Password=${POSTGRES_PASSWORD:-barberpass}"
      # (2) Outras chaves comuns
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB:-barberbook};Username=${POSTGRES_USER:-barber};Password=${POSTGRES_PASSWORD:-barberpass}"
      Database__ConnectionString: "Host=postgres;Port=5432;Database=${POSTGRES_DB:-barberbook};Username=${POSTGRES_USER:-barber};Password=${POSTGRES_PASSWORD:-barberpass}"
      # (3) Variáveis unitárias (caso o código monte a string manualmente)
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-barberbook}
      POSTGRES_USER: ${POSTGRES_USER:-barber}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-barberpass}
      # (4) DATABASE_URL genérica
      DATABASE_URL: "Host=postgres;Port=5432;Database=${POSTGRES_DB:-barberbook};Username=${POSTGRES_USER:-barber};Password=${POSTGRES_PASSWORD:-barberpass}"

      # Redis
      Redis__Host: redis
      Redis__Port: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${API_HOST_PORT:-8080}:8080"

  barberbook-web:
    build:
      context: .
      dockerfile: BarberBook.Web/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5161
      # Base da API para o painel. Ajuste WEB_API_BASE_URL para seu IP se for acessar do celular.
      Api__BaseUrl: ${WEB_API_BASE_URL:-http://host.docker.internal:8080}
      Admin__Username: ${ADMIN_USERNAME:-admin}
      Admin__Password: ${ADMIN_PASSWORD:-admin}
      Admin__TenantId: ${ADMIN_TENANT_ID:-}
    depends_on:
      - barberbook-api
    ports:
      - "${WEB_HOST_PORT:-5161}:5161"

  waha:
    image: devlikeapro/whatsapp-http-api:latest
    environment:
      WHATSAPP_HOOK_URL: "http://n8n:5678/webhook/wa-incoming"
    ports:
      - "${WAHA_HOST_PORT:-3000}:3000"
    volumes:
      - waha_data:/data
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:3000 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  n8n:
    image: n8nio/n8n:stable
    environment:
      N8N_PORT: ${N8N_HOST_PORT:-5678}
      N8N_PROTOCOL: http
      N8N_EDITOR_BASE_URL: "http://localhost:${N8N_HOST_PORT:-5678}"
      GENERIC_TIMEZONE: America/Sao_Paulo
      GEMINI_API_KEY: ${GEMINI_API_KEY:-REPLACE_GEMINI_API_KEY}
    ports:
      - "${N8N_HOST_PORT:-5678}:5678"
    depends_on:
      - barberbook-api
      - waha
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
      - ./automation/n8n:/data/files:ro

volumes:
  db_data:
  redis_data:
  n8n_data:
  waha_data:
