name: Build & Push GHCR
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'BarberBook.Api/**'
      - 'BarberBook.Web/**'
      - 'BarberBook.Api/Dockerfile'
      - 'BarberBook.Web/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta_api
        with:
          images: ghcr.io/${{ secrets.GHCR_USERNAME }}/barberbook-api
          tags: |
            type=raw,value=latest
            type=sha,format=short
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: BarberBook.Api/Dockerfile
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
      - uses: docker/metadata-action@v5
        id: meta_web
        with:
          images: ghcr.io/${{ secrets.GHCR_USERNAME }}/barberbook-web
          tags: |
            type=raw,value=latest
            type=sha,format=short
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: BarberBook.Web/Dockerfile
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}